(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 'Tournament'"
p3
sS'layer'
p4
S'C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\applications\\welcome\\controllers/tournament.py'
p5
sS'code'
p6
S"# coding: utf8\n#\ndef index(): \n    db = DAL('mssql://cheungkt:mechanes5@whale.cs.rose-hulman.edu/SC2tracker')\n    tournies = db().select(db.Tournament.Name)\n    return dict(tourny = tournies)\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\gluon\\restricted.py", line 204, in restricted\n    exec ccode in environment\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\applications\\welcome\\controllers/tournament.py", line 8, in <module>\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\gluon\\globals.py", line 172, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\applications\\welcome\\controllers/tournament.py", line 5, in index\n    tournies = db().select(db.Tournament.Name)\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\gluon\\dal.py", line 5119, in __getattr__\n    return self[key]\n  File "C:\\Users\\mellinja\\Documents\\SC2Tracker\\SC2TourneyTracker\\web2py\\gluon\\dal.py", line 5113, in __getitem__\n    return dict.__getitem__(self, str(key))\nKeyError: \'Tournament\'\n'
p11
s.